---
development:
  cloud_name: ENV['CLOUDINARY_DEV_NAME']
  api_key: ENV['CLOUDINARY_DEV_KEY']
  api_secret: ENV['CLOUDINARY_DEV_SECRET'}]
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ENV['CLOUDINARY_PROD_NAME']
  api_key: ENV['CLOUDINARY_PROD_KEY']
  api_secret: ENV['CLOUDINARY_PROD_SECRET'}]
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ENV['CLOUDINARY_TEST_NAME']
  api_key: ENV['CLOUDINARY_TEST_KEY']
  api_secret: ENV['CLOUDINARY_TEST_SECRET']
  enhance_image_tag: true
  static_image_support: false
